### ISSUE TITLE
Rooms Queries 

### ISSUE THREAD

**Issue by knanahassouna1** [FACG5/Marna-House#11]
# Rooms Queries 
#2 

### Acceptance Criteria : 
- [x] available rooms .
- [x] add Room .
- [x] update Room .  ( stretch goal )  
- [x] Delete Room. ( stretch goal )  
- [x] gerRoomDetails (stretch goal )

**Comment by ashatat** [comment]
I think we should describe in little more details what are the criteria of the available rooms query, for example, the query should get (type, and date ) as inputs to get the available specific type of rooms at the given date?

what do you think? @knanahassouna1 , @donia98

**Comment by knanahassouna1** [comment]
i will do all of that in PR .
:+1:
